### ISSUE TITLE
Support Direct To RPC

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [andersfugmann/amqp-client#23]
RabbitMQ supports a feature called [Direct to](https://www.rabbitmq.com/direct-reply-to.html) which enables the RPC pattern but without creating an actual queue in the background. This may be a bit faster than using proper AMQP queues to do RPC.

From the description on the website it looks like it is very simple to adjust both `Rpc.Client` and optionally `Rpc.Server` to trigger the behaviour to use pseudo-queues instead of actual queues.

**Comment by andersfugmann** [comment]
I do know of this pattern, and It was a deliberate design not to use this for a couple of reasons:
* It is harder (impossible) to track the length on the reply queue. In normal circumstances the queue length should always be zero. If messages starts to build up (e.g. because the queue is not read due to a stalled process), its possible to monitor this, where as a virtual queue cannot be monitored (as far as I know). 
* Rpc (in amqp-client) is not meant to be setup and torn down per request, so queue setup time should not be a problem. A process should only need to call `Rpc.Client.init` once, and use this for all rpc calls. 
* Since the reply-to queue name is known, the system can (and does) listen for dead lettered messages in order to notify the caller if the message is dropped and it becomes known that there will never be a reply. This is done my matching on the reply-to field of messages passing through the `amq_header` exchange. This is not possible with 'amq.rabbitmq.reply-to', as the queue is replaced by an auto generated name in the messages. 
* The feature is a rabbitmq specific feature, and the goal is to be as independent of the amqp server implementation as possible.

In general, I do not see any real advantages using this mechanism, but there are some advantages in using explicitly created reply queues. 

Of course I'm open to be persuaded otherwise.
